In [1]:
import numpy as np
a=np.array([1,2,3])


In [3]:
a[0]

1

In [4]:
a[1
]

2

In [5]:
a[1],a[2]

(2, 3)

In [6]:
a[1,0]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [8]:

a[[0,1,2]]

array([1, 2, 3])

In [9]:
a[::-1]

array([3, 2, 1])

In [17]:
a[0:2]

array([1, 2])

In [10]:
a[::1]



array([1, 2, 3])

In [13]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [19]:
x[1]

array([4, 5, 6])

In [20]:
x[0:0:-1]

array([], shape=(0, 3), dtype=int32)

In [21]:
x[1]=[10,101,10]

In [22]:
x

array([[  1,   2,   3],
       [ 10, 101,  10],
       [  7,   8,   9]])

In [32]:
s=np.sum(a[0])

In [33]:
s

1

In [85]:
x=np.ones([5,5],dtype=int)

In [89]:
np.ones_like(x)*7

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [87]:
d

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [88]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [91]:
np.random.randfloat(10,size=3)

AttributeError: module 'numpy.random' has no attribute 'randfloat'

In [93]:
np.random.randn(3,3,3)

array([[[-0.58018954, -0.80598265,  1.99245625],
        [-0.93694652, -2.37086564, -0.98407176],
        [-0.05797229,  0.98398741,  0.56555417]],

       [[ 0.15602789, -0.31123759,  0.37650069],
        [ 0.5473264 ,  0.96638383, -0.08509012],
        [ 1.17728837, -0.24256766, -0.96062602]],

       [[-0.28599164, -2.16603582,  0.77824212],
        [-0.5514071 , -0.40425951, -0.85993415],
        [-0.8354679 ,  0.35134024,  0.85748152]]])

In [94]:
q=[1,2,3,4,5,6]

In [95]:
np.array(q)

array([1, 2, 3, 4, 5, 6])

In [97]:
x=np.array([1,2,3,4,5,6,7])
y=np.copy(x)
print(y,id(y))

[1 2 3 4 5 6 7] 2369800051888


In [4]:
import pandas as pd

In [5]:
a=pd.Series([1,2,3,4,5,6,7])

In [13]:
q=pd.Series([1,2,3])
index_series=(['sameer','shreya','mihir'])
q.index=index_series
q
q.name='list names'

In [14]:
q

sameer    1
shreya    2
mihir     3
Name: list names, dtype: int64

In [11]:
x=pd.Series(['qqqq','wwww','eeee'])
x[0]

'qqqq'

In [15]:
index_series=(['aa','ss','dd'])
x.index=index_series
x.name='tyuyr'
x

aa    qqqq
ss    wwww
dd    eeee
Name: tyuyr, dtype: object

In [17]:
x(aa)

NameError: name 'aa' is not defined

In [26]:
r=pd.Series(['weer','rtty','tyyu'],index=[1,2,3])
r[3]

'tyyu'

In [57]:
import numpy as np


In [39]:
X = pd.Series(['A','B','C','D','E'],
              index=['first','second','third','forth','fifth'])

#X[['first', 'fifth']]
#X.iloc[[0, -1]]
X[[0, -1]]

C:\Users\goswami\AppData\Local\Temp\1\ipykernel_20464\1500303121.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  X[[0, -1]]


first    A
fifth    E
dtype: object

In [43]:
X = pd.Series(['A','B','C','D','E'],
              index=['first','second','third','forth','fifth'])
X[[0, -1]]

C:\Users\goswami\AppData\Local\Temp\1\ipykernel_20464\1594327124.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  X[[0, -1]]


first    A
fifth    E
dtype: object

In [53]:
e=pd.Series([1,2,3],dtype=int)
e

0    1
1    2
2    3
dtype: int32

In [58]:
pd.Series(e,dtype=np.float)

AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [59]:
X = pd.Series([1,2,3,4,5],
              index=['first','second','third','forth','fifth'])

pd.Series(X, dtype=np.float)

AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [66]:
X = pd.Series([4,2,5,1,3],
              index=['forth','second','fifth','first','third'])

X = X.sort_values()
X

first     1
second    2
third     3
forth     4
fifth     5
dtype: int64

forth     1
second    2
fifth     3
first     4
third     5
dtype: int64

In [71]:
r=pd.Series([5,3,1,2,4],index=['five','three','one','two','four'])
r=r.sort_values()
r

one      1
two      2
three    3
four     4
five     5
dtype: int64

In [76]:
r=pd.Series([5,3,1,2,4],index=['five','three','one','two','four'])
r=r.sort_values()
r[3]=10
r

C:\Users\goswami\AppData\Local\Temp\1\ipykernel_20464\1714277985.py:3: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  r[3]=10


one       1
two       2
three     3
four     10
five      5
dtype: int64

In [78]:
r+=5
r

one       6
two       7
three     8
four     15
five     10
dtype: int64

In [81]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])

X <= 0


0     True
1    False
2     True
3     True
4    False
5    False
6     True
7     True
8     True
9    False
dtype: bool

In [85]:
X = pd.Series([-1,2,0,-4,5,6,0,0,-9,10])
A=X<=0
X[A]

0   -1
2    0
3   -4
6    0
7    0
8   -9
dtype: int64

In [94]:

d=pd.Series([8,9,77,55,67,1,11],index=[0,1,2,3,4,5,6])
s=d>5
s

0     True
1     True
2     True
3     True
4     True
5    False
6     True
dtype: bool

In [93]:
X = pd.Series([-0,2,1,-4,5,6,1,1,-9,10])

X.any()

True

In [104]:
d[0:6]

0     8
1     9
2    77
3    55
4    67
5     1
dtype: int64

In [106]:
c=pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f'])


In [107]:
c


a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [111]:
c['a':'f']

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [112]:
import pandas as pd

# Creating a DataFrame from a dictionary

data = {'Name': ['John', 'Alice', 'Bob'],

        'Age': [28, 24, 22],

        'City': ['New York', 'San Francisco', 'Los Angeles']}

df = pd.DataFrame(data)

In [114]:
df

Name  Age           City
0   John   28       New York
1  Alice   24  San Francisco
2    Bob   22    Los Angeles

In [115]:
df.index(1)

TypeError: 'RangeIndex' object is not callable